import {
  Table,
  Column,
  Model,
  DataType,
  PrimaryKey,
  Default,
  AllowNull,
  CreatedAt,
  UpdatedAt,
} from 'sequelize-typescript';

// @Table configures the Sequelize model metadata
//   tableName: explicit name prevents unexpected pluralization (notes vs note)
//   timestamps: true enables the createdAt and updatedAt columns
@Table({ tableName: 'notes', timestamps: true })
export class Note extends Model {
  // UUID primary key — generated by Sequelize at the JavaScript layer before INSERT
  // @Default(DataType.UUIDV4) means Sequelize generates the UUID itself,
  // which works on any PostgreSQL version without needing the uuid-ossp extension
  @PrimaryKey
  @Default(DataType.UUIDV4)
  @Column(DataType.UUID)
  id!: string;

  // The ! (non-null assertion) tells TypeScript "trust me, this will be set"
  // Sequelize sets all properties after loading from the database — not in the constructor
  // strictPropertyInitialization: false in tsconfig.json is what makes this work

  @AllowNull(false)
  @Column(DataType.STRING)
  title!: string;

  @AllowNull(false)
  @Column(DataType.TEXT)
  description!: string;

  // @CreatedAt and @UpdatedAt tell sequelize-typescript which columns to use
  // for automatic timestamp management — Sequelize sets these on INSERT and UPDATE
  @CreatedAt
  createdAt!: Date;

  @UpdatedAt
  updatedAt!: Date;
}
